---

- name: adding Inetsim archive signing key
## inetsim.org seems unreliable
#  apt_key: url=http://www.inetsim.org/inetsim-archive-signing-key.asc state=present
  apt_key: data="{{ lookup('file', 'inetsim-archive-signing-key.asc') }}" state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: adding Inetsim repository
  apt_repository: repo='deb http://www.inetsim.org/debian/ binary/' state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure Inetsim package is present
  package:
    name: inetsim
    state: present

- stat: path=/etc/inetsim/inetsim.conf
  register: inetsim
- name: Configuring INetSim
  replace:
    dest=/etc/inetsim/inetsim.conf regexp={{ item.regexp }} replace="{{ item.replace }}"
  with_items:
    - { regexp: "toto", replace: "tata" }
  when: inetsim.stat.exists
#    inetsim_services="dns tftp irc ntp finger ident syslog time_tcp time_udp daytime_tcp daytime_udp echo_tcp echo_udp discard_tcp discard_udp quotd_tcp quotd_udp chargen_tcp chargen_udp dummy_tcp dummy_udp"
#    for INETSIM_SERVICE in $inetsim_services; do
#      sed -i -e "/start_service $INETSIM_SERVICE/ s/^#*/#/" /etc/inetsim/inetsim.conf
#    done

- stat: path=/var/log/inetsim/main.log
  register: inetsimlog
- name: Configuring INetSim logs
  file: dest="{{ item }}" mode=0664 state=touch
  with_items:
    - /var/log/inetsim/service.log
    - /var/log/inetsim/debug.log
    - /var/log/inetsim/main.log
  when: not inetsimlog.stat.exists
