---

- name: adding Microsoft packages signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: adding Microsoft prod packages repository
  apt_repository:
    repo: "deb [arch=amd64] http://packages.microsoft.com/ubuntu/{{ ansible_distribution|lower }}/prod {{ ansible_distribution_release }} main"
    filename: microsoft.list
    state: present

- name: Ensure microsoft-vscode package is present
  package:
    name: microsoft-vscode
    state: present
  register: pkg_result
  until: pkg_result is success
