---

- name: adding Microsoft packages signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: adding Microsoft prod packages repository
  apt_repository:
    repo: "deb [arch=amd64] http://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
    filename: microsoft.list
    state: present
