---
# alternative: use snap?

- name: Adding Microsoft packages signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Adding Microsoft packages repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main'
    filename: vscode.list
    state: present

- name: Ensure microsoft-vscode package is present
  ansible.builtin.package:
    name: code
    state: present
  register: pkg_result
  until: pkg_result is success
