---

- name: Adding Microsoft packages signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Adding Microsoft prod packages repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
    filename: microsoft.list
    state: present

- name: Ensure Microsoft packages are present
  ansible.builtin.package:
    name: "{{ microsoft_dotnet }}"
    state: present
