---

- name: Check current apt keys
  ansible.builtin.command:
    cmd: ls -l /usr/share/keyrings/ /etc/apt/keyrings/
  changed_when: false
  failed_when: false
- name: Check current sources.list
  ansible.builtin.command:
    cmd: ls -l /etc/apt/sources.list.d/
  changed_when: false
  failed_when: false
- name: Check if any microsoft sources.list
  ansible.builtin.command:
    cmd: cat /etc/apt/sources.list.d/*microsoft*.list
  changed_when: false
  failed_when: false

- name: Add repo using key from URL
  ansible.builtin.deb822_repository:
    name: microsoft
    types: deb
    uris: "http://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod"
    suites: '{{ ansible_distribution_release }}'
    components: main
    architectures: amd64
    signed_by: https://packages.microsoft.com/keys/microsoft.asc

- name: Ensure Microsoft packages are present
  ansible.builtin.package:
    name: "{{ microsoft_dotnet }}"
    state: present
