---

- name: Add repo using key from URL
  ansible.builtin.deb822_repository:
    name: microsoft
    types: deb
    uris: "http://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod"
    suites: '{{ ansible_distribution_release }}'
    components: main
    architectures: amd64
    signed_by: https://packages.microsoft.com/keys/microsoft.asc

- name: Ensure Microsoft packages are present
  ansible.builtin.package:
    name: "{{ microsoft_dotnet }}"
    state: present
