---
# https://github.com/REMnux/salt-states/tree/master/remnux/repos

# https://launchpad.net/~remnux/+archive/ubuntu/stable
- name: adding REMnux repository
  apt_repository: repo='ppa:remnux/stable' state=present
  when: >
    ansible_distribution == 'Ubuntu' and (
      ansible_distribution_release == 'trusty' or
      ansible_distribution_release == 'bionic' or
      ansible_distribution_release == 'focal'
    )
  register: apt_result
  until: apt_result is success

# https://launchpad.net/~sift/+archive/ubuntu/stable
- name: adding SIFT repository
  apt_repository: repo='ppa:sift/stable' state=present
  when: >
    ansible_distribution == 'Ubuntu' and (
      ansible_distribution_release == 'trusty' or
      ansible_distribution_release == 'xenial' or
      ansible_distribution_release == 'bionic' or
      ansible_distribution_release == 'focal'
    )
  register: apt_result
  until: apt_result is success

## Alternative: trusty-backports?
- name: install draios apt gpg key
  apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
  register: pkg_result
  until: pkg_result is success

- name: adding Draios repository (sysdig)
  apt_repository: repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/' state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success

# These repositories are needed for REMnux, but are disabled on some Ubuntu 14.04 base builds, so enable them.

- name: Enabling Universe repository
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty universe' state=present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
  register: pkg_result
  until: pkg_result is success
- name: Enabling multiverse repository
  replace:
    dest: /etc/apt/sources.list
    regexp: '^#(\.*)multiverse$'
    replace: '\1multiverse'
    mode: '0644'
    backup: yes
