---
# https://github.com/REMnux/salt-states/tree/master/remnux/repos

- name: Install Remnux gpg key
  ansible.builtin.apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbff45016788de115"
    state: present
  register: pkg_result
  until: pkg_result is success

# https://launchpad.net/~remnux/+archive/ubuntu/stable
- name: Adding REMnux repository
  ansible.builtin.apt_repository: repo='ppa:remnux/stable' state=present
  when: >
    ansible_distribution == 'Ubuntu' and (
      ansible_distribution_release == 'bionic' or
      ansible_distribution_release == 'focal'
    )
  register: apt_result
  until: apt_result is success

# https://launchpad.net/~sift/+archive/ubuntu/stable
- name: Adding SIFT repository
  ansible.builtin.apt_repository: repo='ppa:sift/stable' state=present
  when: >
    ansible_distribution == 'Ubuntu' and (
      ansible_distribution_release == 'bionic' or
      ansible_distribution_release == 'focal'
    )
  register: apt_result
  until: apt_result is success

- name: Install draios apt gpg key
  ansible.builtin.apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
  register: pkg_result
  until: pkg_result is success

- name: Adding Draios repository (sysdig)
  ansible.builtin.apt_repository: repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/' state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success

- name: Enabling multiverse repository
  ansible.builtin.replace:
    dest: /etc/apt/sources.list
    regexp: '^#(\.*)multiverse$'
    replace: '\1multiverse'
    mode: '0644'
    backup: yes

- name: Adding wireshark-dev ppa repository
  ansible.builtin.apt_repository:
    repo: 'ppa:wireshark-dev/stable'
    state: present
