---

- name: Debian | x11 packages install
  apt: name=xinit state=present
  register: pkg_result
  until: pkg_result is success

- name: Debian | REMNUX x11 packages install (lxde)
  apt:
    name:
      - xinit
#      - lubuntu-desktop
#      - lightgdm
      - lxde
      - lxdm
    state: present
  when: remnux_x11_env is defined and remnux_x11_env
  register: pkg_result
  until: pkg_result is success

- include: menus-lxde.yml
  when: remnux_x11_env is defined and remnux_x11_env

- name: Setting up auto-login for user {{ remnux_user }}
  replace:
    dest: '/etc/lxdm/lxdm.conf'
    regexp: '^#\ autologin=dgod'
    replace: "autologin={{ remnux_user }}"
  when: remnux_x11_env is defined and remnux_x11_env
- name: disable user list at lxdm greeter
  replace: dest='/etc/lxdm/lxdm.conf' regexp='^disable=\d+$' replace='disable=1'
  when: remnux_x11_env is defined and remnux_x11_env
- name: Fix an error that would be otherwise seen when the user logs out using the GUI - pam_systemd
  lineinfile: dest=/etc/pam.d/lxdm regexp='^session required pam_systemd.so' line='session required pam_systemd.so'
  when: remnux_x11_env is defined and remnux_x11_env

- name: ensure lxdm service is started and enabled
  service: name=lxdm state=started enabled=yes
  when: remnux_x11_env is defined and remnux_x11_env
