---

- name: Debian | x11 packages install
  ansible.builtin.apt:
    name: xinit
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Debian | REMNUX x11 packages install (lxde)
  ansible.builtin.apt:
    name:
      - xinit
      # - lubuntu-desktop
      # - lightgdm
      - lxde
      - lxdm
    state: present
  when: remnux_x11_env is defined and remnux_x11_env
  register: pkg_result
  until: pkg_result is success

- name: Import menus-lxde
  ansible.builtin.import_tasks: menus-lxde.yml
  when: remnux_x11_env is defined and remnux_x11_env

- name: Setting up auto-login for user {{ remnux_user }}
  ansible.builtin.replace:
    dest: '/etc/lxdm/lxdm.conf'
    regexp: '^#\ autologin=dgod'
    replace: "autologin={{ remnux_user }}"
    mode: '0644'
  when: remnux_x11_env is defined and remnux_x11_env
- name: Disable user list at lxdm greeter
  ansible.builtin.replace:
    dest: '/etc/lxdm/lxdm.conf'
    regexp: '^disable=\d+$'
    replace: 'disable=1'
    mode: '0644'
  when: remnux_x11_env is defined and remnux_x11_env
- name: Fix an error that would be otherwise seen when the user logs out using the GUI - pam_systemd
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/lxdm
    regexp: '^session required pam_systemd.so'
    line: 'session required pam_systemd.so'
    mode: '0644'
  when: remnux_x11_env is defined and remnux_x11_env

- name: Ensure lxdm service is started and enabled
  ansible.builtin.service:
    name: lxdm
    state: started
    enabled: yes
  when: remnux_x11_env is defined and remnux_x11_env
